name: Create release and upload to Apple and Google
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build ios and android package
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 25 # For sentry releases

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: nebula/go.sum

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'

      - name: Setup bundletool for APK generation
        uses: amyu/setup-bundletool@f7a6fdd8e04bb23d2fdf3c2f60c9257a6298a40a


      - name: Get build name and number, install dependencies
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

          flutter pub get

          touch env.sh

          cd android
          echo "BUILD_NUMBER=1" >> $GITHUB_ENV
          BUILD_NAME="0.4.3" # strip the front refs/tags/v off
          echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV


      - name: Build Android
        run: |
          flutter build appbundle --build-number="$BUILD_NUMBER" --build-name="$BUILD_NAME"

          # verify that the github token didn't make it into the output
          mkdir -p build/app/test-android
          cp build/app/outputs/bundle/release/app-release.aab build/app/test-android
          cd build/app/test-android
          unzip app-release.aab

  
      - name: Rename app bundle
        run: |
          mv build/app/outputs/bundle/release/app-release.aab \
            build/app/outputs/bundle/release/MobileNebula.aab

      # - name: Create GitHub Release
      #   id: create_release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     name: Release ${{ github.ref }}
      #     draft: true
      #     prerelease: false
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     files: |
      #       build/app/outputs/bundle/release/MobileNebula.aab
